### PR TITLE
Split tests into multiple files.

### LINKED ISSUE #49: Split tests
The tests currently all reside in `tests/test.c` and use both public and non-public API. It would be good to split tests for different functions up (with a common file for the utility functions). That also allows us to have separate test suites for public and non-public API.

### PR DESCRIPTION
**Pull request by Airblader**
This is a first step to clean up the test suite. This commit splits the
tests into multiple files.

fixes #49

### CODE REVIEW

**Comment by Airblader** [comment]
This is a first step to split the files. The next step is to move to xvfb via wrapper.

**Comment by psychon** [comment]
A first suggestion is to amend the following into the commit (but I'm working on another additional suggestion):
```diff
diff --git a/Makefile.am b/Makefile.am
index 2158ba8..6e1e3fe 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -17,7 +17,6 @@ dist-hook: ChangeLog INSTALL
 EXTRA_DIST = autogen.sh xcb-xrm.pc.in include/xcb_xrm.h include/database.h
 EXTRA_DIST += include/entry.h include/externals.h include/match.h
 EXTRA_DIST += include/resource.h include/util.h
-EXTRA_DIST += tests/tests_utils.c tests/tests_parser.c tests/tests_match.c tests/tests_database.c
 EXTRA_DIST += tests/resources
 
 lib_LTLIBRARIES = libxcb-xrm.la
@@ -36,19 +35,17 @@ pkgconfig_DATA = xcb-xrm.pc
 TESTS = tests/tests_parser tests/tests_match tests/tests_database
 check_PROGRAMS = $(TESTS)
 
-tests_tests_utils_SOURCE = tests/tests_utils.c
-
-tests_tests_parser_SOURCE = tests/tests_utils.c tests/tests_parser.c
+tests_tests_parser_SOURCES = tests/tests_utils.c tests/tests_parser.c
 tests_tests_parser_CPPFLAGS = -I$(srcdir)/include/ $(XCB_CFLAGS)
 tests_tests_parser_LDADD = libxcb-xrm.la $(XCB_LIBS)
 tests_tests_parser_LDFLAGS = $(TEST_LIBS)
 
-tests_tests_match_SOURCE = tests/tests_utils.c tests/tests_match.c
+tests_tests_match_SOURCES = tests/tests_utils.c tests/tests_match.c
 tests_tests_match_CPPFLAGS = -I$(srcdir)/include/ $(XCB_CFLAGS)
 tests_tests_match_LDADD = libxcb-xrm.la $(XCB_LIBS)
 tests_tests_match_LDFLAGS = $(TEST_LIBS)
 
-tests_tests_database_SOURCE = tests/tests_utils.c tests/tests_database.c
+tests_tests_database_SOURCES = tests/tests_utils.c tests/tests_database.c
 tests_tests_database_CPPFLAGS = -I$(srcdir)/include/ $(XCB_CFLAGS)
 tests_tests_database_LDADD = libxcb-xrm.la $(XCB_LIBS)
 tests_tests_database_LDFLAGS = $(TEST_LIBS)
```

**Comment by Airblader** [comment]
Thanks, I've added that patch. :-)

**Comment by psychon** [comment]
Thanks. :+1: 
One day I will eventually produce my own commits. That day is not now. ;-)

**Comment by Airblader** [comment]
I'm looking forward to it. I feel a little bad for taking the commits away from you, but I try to mention you in each one. :) Thanks for all the support, this has been and hopefully will continue to be extremely helpful.

**Pull request merged**
