### PR TITLE
Resolve directories in #include statements correctly.

### LINKED ISSUE #47: Handle relative filenames correctly
See #33, relative filenames in `#include` statements must be handled relative to the file they occur in, according to the specification.

### PR DESCRIPTION
**Pull request by Airblader**
With this commit, we now resolve the directories for the files in #include
directives according to the specification, i.e., by handling relative
paths as relative to the file containing the #include directory.

Furthermore, this fixes a couple of memory leaks showing up due to the new
tests.

fixes #47

### CODE REVIEW

**Comment by psychon** [comment]
Nice! (Except for the failed tests...)

**Comment by Airblader** [comment]
Yeah, I have to figure out why they fail. Locally they run fine. It's still a little unsatisfying that `make check` will only run correctly when run under `xvfb-run` now, though.

**Comment by psychon** [comment]
If I ever find the time (grml... :-( ), I can do something about that. I'm thinking of a test that uses `xvfb-run` if present and otherwise exits with code 77 (AFAIR that should be the exit code signalling a skipped test).

That way you could also use `xrdb` from the shell script to set up some known state and check in the test that the library reads that correctly.

**Comment by Airblader** [comment]
Yeah, that'd be cool. For now it's good enough if we at least ensure test coverage.

**Comment by psychon** [comment]
I'll do what I've always been doing so far: I help you to help yourself.
The following diff should help you figure out everything you need. It adds a shell script that can set up the test environment (e.g. start an X11 server, use `xrdb` to set the right properties etc) and then runs the real test (and I was right, exit status `77` signals "skipped")
```diff
diff --git a/Makefile.am b/Makefile.am
index bd9fe30..c5b6281 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -14,7 +14,8 @@ ChangeLog:
 
 dist-hook: ChangeLog INSTALL
 
-EXTRA_DIST = autogen.sh xcb-xrm.pc.in include/xcb_xrm.h include/database.h
+EXTRA_DIST = autogen.sh xcb-xrm.pc.in tests/xvfb-test-runner.sh
+EXTRA_DIST += include/xcb_xrm.h include/database.h
 EXTRA_DIST += include/entry.h include/externals.h include/match.h
 EXTRA_DIST += include/resource.h include/util.h
 
@@ -31,8 +32,8 @@ libxcb_xrm_la_LDFLAGS = -version-info 0:0:0 -no-undefined -export-symbols-regex
 
 pkgconfig_DATA = xcb-xrm.pc
 
-TESTS = tests/test
-check_PROGRAMS = tests/test
+TESTS = tests/test tests/xvfb-test-runner.sh
+check_PROGRAMS = tests/test tests/xvfb-test
 tests_test_SOURCE = tests/test.c
 tests_test_CPPFLAGS = -I$(srcdir)/include/ $(XCB_CFLAGS)
 tests_test_LDADD = libxcb-xrm.la $(XCB_LIBS)
diff --git a/tests/xvfb-test-runner.sh b/tests/xvfb-test-runner.sh
new file mode 100755
index 0000000..1a525a1
--- /dev/null
+++ b/tests/xvfb-test-runner.sh
@@ -0,0 +1,3 @@
+#!/bin/sh
+command -V xvfb-run || exit 77 # Skip test if no xvfb-run in $PATH
+exec xvfb-run tests/xvfb-test
diff --git a/tests/xvfb-test.c b/tests/xvfb-test.c
new file mode 100644
index 0000000..cf4b1cf
--- /dev/null
+++ b/tests/xvfb-test.c
@@ -0,0 +1,7 @@
+#include <stdio.h>
+
+int main(void)
+{
+	puts("I live!");
+	return 0;
+}
```

**Comment by Airblader** [comment]
@psychon I'm wondering whether we should omit this handcrafted stuff and instead just put the file through the C preprocessor. This would not only take care of `#include`, but also allow things like `#define` which don't strictly appear in the spec, but are respected by `xrdb` (which also uses a preprocessor).

**Comment by psychon** [comment]
Hm, xrdb only runs the preprocess in xrdb. This is not done in Xlib. So no, that's not what Xlib is doing and it'd be weird to have a library depend on a C preprocessor.
Also, xrdb's code is weird ;-) https://sources.debian.net/src/x11-xserver-utils/7.7%2B7/xrdb/xrdb.c/#L1307-L1330

However, this means that writing your own `xrdb` is now harder to do.

(Side note: I looked into Xlib's source: It has a limit of 100 on the inclusion depth. After recursively following 100 includes, it starts silently ignoring include directives (100 includes next to each other are fine, I'm talking about recursive ones!); look for `MAXDBDEPTH` in `src/Xrm.c`)

**Comment by Airblader** [comment]
Alright, let's stick with this then. In general, people should properly load `RESOURCE_MANAGER` (via xrdb) anyway and then they can use their preprocessor. I was mostly thinking of applications like rofi which use the Xresources format to load configuration from dedicated files. But I think this is OK.

> I looked into Xlib's source: It has a limit of 100 on the inclusion depth.

I'm guessing they did this to prevent accidental endless loops. It might not be such a bad idea to have this.

**Comment by Airblader** [comment]
Also sidenote, I love this:

````
else {
		/*
		 * Magic unspecified feature #254.
		 *
		 * If two separators appear with no Text between them then
		 * ignore them.
		 *
		 * If anyone of those separators is a '*' then the binding
		 * will be loose, otherwise it will be tight.
		 */

		if (c == '*')
		    *t_bindings = XrmBindLoosely;
	    }
```

**Pull request merged**
