### PR TITLE
autogen.sh: respect the NOCONFIGURE env var

### PR DESCRIPTION
**Pull request by nektro**

### CODE REVIEW

**Comment by Airblader** [comment]
Thanks for the PR! Out of curiosity, do you actively need this (e.g. for package publishing or something), or is this just as "it's supposed to be that way" change?

**Comment by nektro** [comment]
np :) the latter. in my packager I control the commands so I was able to work around this in the interim

**Comment by nektro** [comment]
I picked up the pattern from the other upstream xorg libraries, eg https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/blob/master/autogen.sh#L24-32

**Review by Airblader — APPROVED** [review]
Great, thank you so much for the link and the contribution!

**Comment by nektro** [comment]
Yw! and thanks for all your work on i3, its been my daily driver for years :)

**Pull request merged**
